### ISSUE TITLE
When running deploy, PutIntegrationResponse found

### ISSUE THREAD

**Issue by ghost** [Miserlou/Spheres#1]
I ran into this issue when walking through the tutorial. I'm working on resolving the issue but I thought i'd file an issue.

`(env)uiop:Spheres apple$ python manage.py  deploy dev
Packaging project as zip..
Uploading zip (26.0MiB)..
Creating API Gateway routes..                                                                                                        
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/django_zappa/management/commands/deploy.py", line 117, in handle
    api_id = zappa.create_api_gateway_routes(lambda_arn, lambda_name)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/zappa/zappa.py", line 463, in create_api_gateway_routes
    self.create_and_setup_methods(api_id, root_id, lambda_arn)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/zappa/zappa.py", line 582, in create_and_setup_methods
    responseTemplates=response_templates
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/apple/code/Spheres/env/lib/python2.7/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NotFoundException) when calling the PutIntegrationResponse operation: No integration defined for method
(env)uiop:Spheres apple$`

**Comment by Miserlou** [comment]
Thanks for filing!

Can you tell me the exact steps you did this with, and a bit more about your setup?

**Comment by ghost** [comment]
Sure!

I tried to follow your instructions in the youtube video as best I could, After I run the deploy command, I can see the zip file on s3 and the error above comes up. In my apigateway console I see this

![image](https://cloud.githubusercontent.com/assets/1754170/12931279/d0011b1c-cf31-11e5-868e-5dc496cb1969.png)

and in the lambda console I see

![image](https://cloud.githubusercontent.com/assets/1754170/12931294/e1a279ba-cf31-11e5-8b46-4c4f7ba4ba27.png)

![image](https://cloud.githubusercontent.com/assets/1754170/12931325/03b02e1c-cf32-11e5-8bf9-8d5582aef917.png)

I'm running on a macbook. The django app seems to run locally.

I tried running the code in pycharm but I notice weird things seems to happen. The uploaded file is only 85 KB instead of 26 MB. 

the uri variable in zappa.py:create_and_setup_methods has this

`u'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:62arinarinarin:function:spheres-dev/invocations'`

I don't seem to have any apis defined in us-east-1 so maybe that is what it is talking about? 

My aws/config file has

> [default]
> region = us-west-2

**Comment by ghost** [comment]
I changed my region to us-east-1 and that seems to be the issue. :sob:  I'm putting in a fix to configure regions, if it pleases you.
